### ISSUE TITLE
Introduce IDs for one-act plays & original plays

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#125]
In order to provide stable links, even if slugs change (e.g., sometimes they need adjustments/corrections), we discussed to introduce IDs and corresponding stable URIs that would resolve to the URLs as they are applied now (```https://einakter.dracor.org/id/000001``` → ```https://einakter.dracor.org/koenig-die-verkehrte-welt```).

In the YAML data files, it could look like this:

```yaml
id: 000001
slug: koenig-die-verkehrte-welt
author:
  name: König, Johann Ulrich von
  wikidata: Q1696433
title: Die verkehrte Welt
subtitle: Ein Lustspiel in ungebundener Rede
numberOfScenes: 12
[etc.]
```

The same goes for original plays, where we could use a prefix to distinguish them from the German-language plays (also because they have a slightly different data model behind them, see [here](https://github.com/dracor-org/einakter/wiki)):

```yaml
id: ori000001
slug: moliere-l-impromtu-de-versailles
author:
  name: Molière
  wikidata: Q687
title: L'impromtu de Versailles
subtitle: Comédie
[etc.]
```

IDs would be used by external projects like Wikidata, Weber-Gesamtausgabe and [FID DK](https://www.performing-arts.eu/) to link to our project. Thus, IDs would also be used in our BEACON file (see #122).
