### ISSUE TITLE
Allow direct links within dictionary entries

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#25]
Some of our sources are directly linkable, so we should allow direct links, for example:

```yaml
dictionaries:
  corvey: S. 227–228
```
… should be writeable as:

```yaml
dictionaries:
  corvey: [S. 227–228](https://digi20.digitale-sammlungen.de/de/fs1/object/goToPage/bsb00040797.html?pageNo=225)
```

Everything else stays the same, including the link to the main work.

**Comment by cmil** [comment]
The above commit refactors the `dictionaries` property into a list of objects, for example:

```yaml
dictionaries:
  - name: corvey
    pages: S. 227-228
    url: "https://digi20.digitale-sammlungen.de/de/fs1/object/goToPage/bsb00040797.html?pageNo=225"
```

While slightly more verbose this is a safer, less error prone implementation that does not require additional parsing of the string format.

It has been deployed to the staging system, see for instance, https://einakter.staging.dracor.org/muellner-der-angolische-kater-oder-die-koenigin-von-golkonde.
