### ISSUE TITLE
Allow to identify a setting location by Wikidata ID

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#26]
For this we should ~~remodel the `settings`~~ add a `location` property in `data.yaml` as an object like this:

```yaml
setting: "Scene: Paris, im Hause des Banquiers Sarrassin."
location:
  wikidataId: Q90
  coordinates:
    latitude: 48.856944
    longitude: 2.351389
```

Either one of the `wikidataId` and `coordinates` properties would be required for the `location`. The Wikidata ID would allow us to collect and add geo coordinates in a scripted process (see #27). It could even refer us to the Getty Thesaurus of Geographic Names IDs if need be.
