### ISSUE TITLE
Expose KML and CSV file for locations to work in Geo-Browser

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#40]
A good showcase for interoperability: The [DARIAH-DE Geo-Browser](https://geobrowser.de.dariah.eu/) provides historical map overlays, which are interesting for our case. I suggest to expose files with our location data in KML and CSV format, maybe at:
* https://einakter.dracor.org/locations.kml
* https://einakter.dracor.org/locations.csv

It can then directly be loaded into Geo-Browser by providing the URL – we just got the message that our *.dracor.org domains are white-listed for the service.

The USP of Geo-Browser is the connection between space and time, so all entries should carry their normalized year with them. Not sure about other metadata and whether we can provide direct links back to our database in Geo-Browser.

Btw, their use of the file formats can be explored by using the exemplary "Static data" in the pull-down menu.

**Comment by lehkost** [comment]
Little update:
* All additional fields in the CSV version should be automatically displayed in the Geo-Browser. I think that with KML this will not be the case. 
* Links can be part of the description, see examples here:
  * http://www.steinheim-institut.de/daten/csv/epidat_names.csv
  * https://geobrowser.de.dariah.eu?csv1=http://www.steinheim-institut.de/daten/csv/epidat_names.csv

**Comment by cmil** [comment]
What would be the format of the CSV? The http://www.steinheim-institut.de/daten/csv/epidat_names.csv doesn't seem to be available any more.

**Comment by lehkost** [comment]
I think the file was moved here:
- http://www.steinheim-institut.de/daten/epidat-bhb.csv

This would be the link to directly upload this file to the GeoBrowser:
- https://geobrowser.de.dariah.eu/?csv1=http://www.steinheim-institut.de/daten/epidat-bhb.csv

**Comment by lehkost** [comment]
An example for generating the KML format out of an entry in the YAML file:

Example file: [ein000010](https://einakter.dracor.org/id/)
YAML code:
```yaml
---
id: ein000010
slug: alexander-die-verpfaendung
author:
  name: **Alexander, Karl**
  wikidata: Q100989128
title: **Die Verpfändung**
subtitle: Ein Schauspiel in einem Aufzuge
numOfScenes: 15
yearPrinted: 1779
[...]
settings:
  - description: >-
      **Die Handlung ist in London.**
    location:
      **wikidataId: Q84**
  - description: >-
      Das Theater stellt Roberts Wohnung vor, ein reinliches Zimmer, mittelmäßig meublirt, Robert sitzt auf einen Lehnstuhl, sein Tochterkind spielt zwischen seinen Füßen, und Jeny arbeitet beym Tische an einer Manschette.
---
```

Would translate to an entry in the KML document like this:

```kml
<Placemark>
  <address>Die Handlung ist in London.</address>
  <description>https://einakter.dracor.org/id/ein000010</description>
  <name>Alexander, Karl: Die Verpfändung</name>
  <Point>
    <coordinates>-0.1255,51.5084,0</coordinates>
  </Point>
  <TimeStamp>
    <when>1779</when>
  </TimeStamp>
</Placemark>
```

TimeStamp should be the normalised year. We could re-use data used for our [own map of locations](https://einakter.dracor.org/locations).

Instead of putting the permalink into the description, we could also place it onto the title of the play if KML allows.
