### ISSUE TITLE
Separate data file to enhance metadata on original plays?

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#42]
Right now, the original titles of translated one-act plays are stored in our "data.yaml" file like this:

```yaml
basedOn:
  - "Germain François Poullain de Saint-Foix:
    [»Les veuves turques. Comédie en un acte et en prose«]
    (https://books.google.com/books?id=nQakGA16jysC&pg=PA85)"
```

The idea is to enhance and centralise information of original plays as there is often more than one translation, e.g., at least 7 different translations of Molière's "Les précieuses ridicules" (cf. corresponding [commit](https://github.com/dracor-org/einakter/commit/1383f4c256a8ffa88459f16adcc4a8ffc5f26298)).

Since we decided against a relational database model, we have a problem now, there is no straightforward way to do this. My proposition (to be discussed) is to introduce one new file, maybe "originals.yaml", where we collect all original plays. This way, we can easily enhance them and don't have to copy&paste information within "data.yaml", should there be more than one translation of a play. From within "data.yaml", we would now only have to reference the slug of an original:

### "originals.yaml" (suggestion)

```yaml
slug: moliere-les-precieuses-ridicules
author: (or authors)
  name: Molière
  wikidata: Q687
title: Les précieuses ridicules
subtitle: Comédie en un acte, en prose
language: fre
created:
printed: 1660
premiered: 1659
fulltext: http://www.theatre-classique.fr/pages/programmes/edition.php?t=../documents/MOLIERE_PRECIEUSESRIDICULES.xml
ids:
  dracor: fre001021
  wikidata: Q1219041
```

### "data.yaml"

In our "data.yaml" file we would then reference the slug under ```basedOn``` (instead of a string with authors + title):

```yaml
[…]
basedOn: moliere-les-precieuses-ridicules
```

If a play is translated ("Aus dem Französischen" or similar), but doesn't have an original author attributed, we should reference the language instead in a new property (language codes following ISO 639-2?):

```yaml
[…]
basedOnLanguage: fre
```

That's it. When building the single-page app, we could lure in the information from "originals.yaml" and display it like this:

----

Translated from:

* Molière <sub>[Q687](http://www.wikidata.org/entity/Q687)</sub>: [»Les précieuses ridicules. Comédie en un acte, en prose«](http://www.theatre-classique.fr/pages/programmes/edition.php?t=../documents/MOLIERE_PRECIEUSESRIDICULES.xml
) <sub>[Q1219041](http://www.wikidata.org/entity/Q1219041) · [fre001021](https://dracor.org/id/fre001021)</sub> (1659) **&#60;French&#62;**

Other one-act translations:
* Bierling, Friedrich Immanuel: Die lächerlichen Preciösen; oder, die romanmäßig witzigen Frauenzimmer. Ein Lustspiel in einer Handlung (1752)
* Dyk, Johann Gottfried: Der Sprödenspiegel. Ein Lustspiel in Einem Akte. Nach Moliere (1778)
* Schmid, Christian Heinrich: Der Sprödenspiegel. Lustspiel in einem Aufzug, nach Moliere (1779)
* Robert, Ludwig: Die Ueberbildeten: Lustspiel in einem Aufzug nach Moliere's: Précieuses ridicules (1804)
* Zschokke, Heinrich: Die Eleganten. Posse in einem Aufzuge. Von Molieres. Für die deutsche Bühne (1805)
* Robert, Ludwig: Die Ueberbildeten. Lustspiel in einem Aufzuge nach Moliere's »précieuses ridicules«. (Neuere, freie Bearbeitung.) (1824)
* Lax, Louis: Die Verschrobenen. Lustspiel in einem Aufzug (1837)

----

**Comment by cmil** [comment]
Couldn't we just add the original plays to data.yaml, cross-reference them and filter them out when generating `data.json` (omitting any play that has a language specified and that language is not `ger`)?

**Comment by lehkost** [comment]
@cmil is there an advantage of keeping just one file? i think it would confuse the work in that file a bit. but if we stick to that proposition, wouldn't it then be better to add a layer to the hierarchy in the yaml file to avoid confusion, like this:

```yaml
play:
  slug: bierling-die-laecherlichen-precioesen
[…]
original:
  slug: moliere-les-precieuses-ridicules
[…]
```

also, german plays and foreign originals would have slightly different data fields, see above.
