### ISSUE TITLE
Add Ludwig Börne's "Dramaturgische Blätter" to dictionaries

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#54]
Same case as https://github.com/dracor-org/einakter/issues/21 and https://github.com/dracor-org/einakter/issues/22:

```yaml
dictionaries:
  - name: boerne
    pages: Nr. xx, S. yy–zz
    url: […]
```

* Ludwig Börne: Dramaturgische Blätter (1818–1828). Nr. xx, S. yy–zz

For example, [this one-act play](https://einakter.dracor.org/houwald-die-heimkehr) would have nr. + page numbers [Nr. 48, S. 387–393](https://archive.org/details/LudwigBrneSmtlicheSchriftenBd1/page/n415/mode/2up).
