### ISSUE TITLE
Allow multiple authors in "originals.yaml"

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#59]
Case in point: https://einakter.staging.dracor.org/blum-der-baer-und-der-bassa

Should accept:
```yaml
authors:
  name: Eugène Scribe
  wikidata: Q319261
  name: Saintine
  wikidata: Q1399502
```
