### ISSUE TITLE
Curly brackets for groups in cast lists

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#68]
As usual in cast lists, we would like to place descriptions of groups to the right of the group members, with a curly bracket to indicate the affiliation of the corresponding characters.

It was suggested to solve this in CSS:

```css
#noticespan-211:before {
	content: '} ';
	margin-left: 1em;
	font-size: 300%;
	line-height: 25%;
	position: relative;
	top: 0.15em;
	font-style: normal !important;
}
```
One of many examples would be this one ("ihre Töchter."): https://einakter.dracor.org/kotzebue-die-erbschaft
